apiVersion: kafka.strimzi.io/v1beta2
kind: KafkaTopic
metadata:
  name: feedback-topic
  labels:
    strimzi.io/cluster: deep-dive-quarkus
  namespace: deep-dive-quarkus
spec:
  config:
    retention.ms: 604800000
    segment.bytes: 1073741824
  partitions: 10
  replicas: 3
