kind: Secret
apiVersion: v1
metadata:
  name: kafka-config
  namespace: serverless-demo
stringData:
  kafka.bootstrap.servers: serverless-demo-kafka-bootstrap.serverless-demo.svc.cluster.local:9092
type: Opaque