kind: Secret
apiVersion: v1
metadata:
  name: kafka-config
  namespace: deep-dive-quarkus
stringData:
  kafka.bootstrap.servers: deep-dive-quarkus-kafka-bootstrap.deep-dive-quarkus.svc.cluster.local:9092
type: Opaque
