kind: Secret
apiVersion: v1
metadata:
  name: mariadb-config
  namespace: deep-dive-kafka
stringData:
  user: maria
  userPassword: password
  host: mariadb.deep-dive-kafka.svc.cluster.local:3306
  database: feedback
  rootPassword: root
type: Opaque
