kind: Secret
apiVersion: v1
metadata:
  name: mariadb-config
  namespace: serverless-demo
stringData:
  user: maria
  userPassword: password
  host: mariadb.serverless-demo.svc.cluster.local
  database: feedback
  rootPassword: root
type: Opaque